#ifndef MATCHING_ENGINE_H
#define MATCHING_ENGINE_H

#include "Order.h"
#include "include/Instrument.h"

#include <chrono>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <map>
#include <unordered_map>
#include <vector>

// Returned from add_order. `status` reflects the final disposition (ACK
// rested / FILLED / PARTIALLY_FILLED rested / CANCELED IOC residual /
// REJECTED). `fills` holds any maker fills generated by the marketable
// portion (empty for pure-rest POST_ONLY).
struct SubmitResult {
    OrderStatus            status;
    std::vector<FillEvent> fills;
};

// Single-instrument limit order book with O(1) cancel/amend.
//   bids_ / asks_ : std::map<Ticks, Level> — price-level index
//   Level         : intrusive doubly-linked FIFO of OrderNodes at one price
//   lookup_       : unordered_map<order_id, OrderNode*> — O(1) handle
//
// Memory: OrderNodes are heap-allocated on rest, deleted on cancel/full
// fill. The engine owns every node it holds a pointer to. (Arena/pool
// allocation is M5 work.)
class MatchingEngine {
public:
    MatchingEngine();
    ~MatchingEngine();
    MatchingEngine(const MatchingEngine&) = delete;
    MatchingEngine& operator=(const MatchingEngine&) = delete;

    // Submit a new order. Behavior depends on `type`:
    //   POST_ONLY  — rejected if marketable, otherwise rests.
    //   LIMIT      — matches against book, residual rests at limit price.
    //   IOC        — matches against book, residual canceled.
    // `aggressor_trade_id` tags any generated FillEvents (ignored for
    // pure-rest POST_ONLY).
    SubmitResult add_order(Order order, OrderType type,
                           uint64_t aggressor_trade_id = 0);

    // O(1) cancel by id. Returns false if id not resting.
    bool cancel_order(uint64_t id);

    // NASDAQ-style amend:
    //   same price + new_qty <= leaves_qty : queue position preserved
    //   same price + new_qty >  leaves_qty : position lost (requeued at tail)
    //   different price                     : position lost (requeued at tail)
    //   amend would cross opposite side     : REJECTED
    //   new_qty/new_price non-positive      : REJECTED
    //   id not resting                      : returns false
    bool amend_order(uint64_t id, Ticks new_price, int new_qty,
                     std::chrono::system_clock::time_point ts);

    // ---- Inspection (replaces old vector accessors) ------------------

    bool        empty(Side s) const;
    std::size_t num_levels(Side s) const;
    std::size_t num_orders(Side s) const;
    // Precondition: !empty(s).
    Ticks       best_price(Side s) const;
    std::size_t orders_at_depth(Side s, std::size_t depth) const;
    int         qty_at_depth(Side s, std::size_t depth) const;
    Ticks       price_at_depth(Side s, std::size_t depth) const;
    // 0 if (depth, pos) is out of range.
    uint64_t    order_id_at_queue_pos(Side s, std::size_t depth,
                                       std::size_t pos) const;
    bool        contains(uint64_t id) const;
    int         leaves_qty_of(uint64_t id) const;       // -1 if not resting
    OrderStatus status_of(uint64_t id) const;           // CANCELED if not resting

private:
    struct OrderNode {
        uint64_t      order_id;
        Side          side;
        OrderType     type;
        Ticks         price;
        int           original_qty;
        int           leaves_qty;
        OrderStatus   status;
        std::chrono::system_clock::time_point created_at;
        std::chrono::system_clock::time_point updated_at;
        OrderNode*    prev;
        OrderNode*    next;
    };

    struct Level {
        OrderNode* head      = nullptr;
        OrderNode* tail      = nullptr;
        int        total_qty = 0;

        void push_back(OrderNode* n);
        // Unlinks `n` and adjusts total_qty by n->leaves_qty. Caller is
        // responsible for erasing the (now-empty) Level from the book.
        void unlink(OrderNode* n);
        bool empty() const { return head == nullptr; }
    };

    using BidBook = std::map<Ticks, Level, std::greater<Ticks>>;
    using AskBook = std::map<Ticks, Level, std::less<Ticks>>;

    BidBook bids_;
    AskBook asks_;
    std::unordered_map<uint64_t, OrderNode*> lookup_;

    bool would_cross(Side incoming_side, Ticks price) const;

    // Match `qty` of `aggressor_side` against the opposite book up to
    // `limit_price`. Appends fills, returns unmatched remainder.
    int match_against_book(Side aggressor_side, Ticks limit_price, int qty,
                           uint64_t aggressor_trade_id,
                           std::chrono::system_clock::time_point ts,
                           std::vector<FillEvent>& fills);

    void unlink_node_from_book(OrderNode* n);
    void rest_node(OrderNode* n);
};

#endif // MATCHING_ENGINE_H
